# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-20 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_icons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuicon',
            name='menu_class_for_link_icon',
            field=models.CharField(blank=True, max_length=48, null=True, verbose_name='Menu Class for Link Icon'),
        ),
    ]
